### ISSUE TITLE
Multi-Column Morphology

### ISSUE THREAD

**Issue by celsomilne** [ellispatrick/spicyR#3]
Should `SegmentedCells` accommodate multi-column morphology data? For example:

```R
library(spicyR)
df <- data.frame(x=runif(100),
                 y=runif(100),
                 area=runif(100)^2*pi,
                 circularity=runif(100)^2*pi,
                 cellType=runif(100) >= 0.5)
SegmentedCells(df, morphologyString = c("area", "circularity"))
```

**Comment by ellispatrick** [comment]
It already should. Try using morphologyString = "shape_" with "shape_area" and "shape_circularity" in the df.

**Comment by celsomilne** [comment]
Great, that works! Would it be good to have functionality similar to that mentioned in #5?
