### ISSUE TITLE
vignette unclear

### ISSUE THREAD

**Issue by SchulzDan** [ellispatrick/spicyR#39]
Hi,

I am confused with the way that the condition comparisons are performed. In the vignette you use the diabetesData_SCE object and for condition you use the `stage` entry. However, this entry contains three levels! Which comparison is actually made here?

Many thanks for clarification.

Best,
Daniel

**Comment by alexrunqin** [comment]
Hi Daniel! 

Good observation - by default, spicyR uses the first 2 levels of your specified factor column and compares these, with the first level being considered the "base" group. The vignette does not currently cover this, and has now been updated to reflect that.

When actually using the `spicy()` function there is a warning notification that mentions this, and if you would like to change the conditions being compared, feel free to change the ordering of the levels for your input into the `condition = ` parameter.

Best,
Alex
